# ⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️⚖️

# | **Intent**       | **Count** |
# | ---------------- | --------- |
# | `general`        | 135       |
# | `realtime`       | 93        |
# | `system`         | 92        |
# | `open`           | 79        |
# | `play`           | 79        |
# | `content`        | 69        |
# | `google search`  | 68        |
# | `close`          | 65        |
# | `reminder`       | 62        |
# | `exit`           | 54        |
# | `youtube search` | 41        |
# | `generate image` | 30        |




import pandas as pd
from time import sleep 

# Load the existing CSV
csv_path = r"/home/ranjit/Desktop/Decision_Making_Model/Cleaned_Intent_Dataset.csv"
df = pd.read_csv(csv_path)


def remove_specific_utterance(csv_path, utterance_to_remove):
    # Load the dataset
    df = pd.read_csv(csv_path)

    # Check if the utterance exists
    if utterance_to_remove in df['utterance'].values:
        print(f'Found: "{utterance_to_remove}". Removing it...')
        sleep(3)
        #where the mask evaluates to "True" are kept, and the rows where the mask evaluates to "False" are discarded.
        df = df[df['utterance'] != utterance_to_remove]

        # Save the updated DataFrame back to the original CSV
        df.to_csv(csv_path, index=False)
        print(f'Updated dataset saved to: {csv_path}')
    else:
        print(f'"{utterance_to_remove}" not found in dataset.')

    return df
df


def append_to_intent_dataset(csv_path: str, dataset: list[tuple[str, str]]):
    """
    Appends a list of (utterance, intent) tuples to the specified intent CSV file.

    Args:
        csv_path (str): Path to the CSV file.
        dataset (List[Tuple[str, str]]): List of (utterance, intent) pairs.
    """
    try:
        # Load existing CSV
        df = pd.read_csv(csv_path)

        # Prepare new data as DataFrame
        new_data = pd.DataFrame(dataset, columns=['utterance', ' intent'])

        # Append and remove any duplicate rows
        df = pd.concat([df, new_data], ignore_index=True)
        df.drop_duplicates(inplace=True)

        # Save back to CSV
        df.to_csv(csv_path, index=False)
        print(f"✅ Successfully appended {len(new_data)} records to {csv_path}")
    except Exception as e:
        print(f"❌ Failed to append data: {e}")




dataset = [

    # EXIT
    ("exit the application", "exit"),
    ("close this app", "exit"),
    ("can you shut down?", "exit"),
    ("please terminate the session", "exit"),
    ("stop running now", "exit"),
    ("leave the program", "exit"),
    ("turn yourself off", "exit"),
    ("abort mission", "exit"),
    ("I'm done, close it", "exit"),
    ("that's enough, exit now", "exit"),
    ("exit the app", "exit"),
    ("close this down", "exit"),
    ("please stop everything", "exit"),
    ("I want to quit", "exit"),
    ("terminate the program", "exit"),
    ("can you exit?", "exit"),
    ("shut it off", "exit"),
    ("I'm done, close it", "exit"),
    ("turn off the assistant", "exit"),
    ("leave the session", "exit"),
    ("wrap it up", "exit"),
    ("kill the process", "exit"),
    ("that's enough, stop", "exit"),
    ("I want to leave", "exit"),
    ("close and quit now", "exit"),
    ("end the program", "exit"),
    ("log out now", "exit"),
    ("please exit", "exit"),
    ("close it down", "exit"),
    ("shut down the assistant", "exit"),
    ("terminate the session", "exit"),
    ("quit the app", "exit"),
    ("stop everything", "exit"),
    ("close the program", "exit"),
    ("exit the application", "exit"),
    ("close this app", "exit"),
    ("can you shut down?", "exit"),
    ("please terminate the session", "exit"),
    ("stop running now", "exit"),
    ("leave the program", "exit"),
    ("turn yourself off", "exit"),
    ("abort mission", "exit"),
    ("I'm done, close it", "exit"),
    ("that's enough, exit now", "exit"),

    # GENERAL
    ("hey", "general"),
    ("how are you doing?", "general"),
    ("hi there!", "general"),
    ("how are you doing?", "general"),
    ("good morning", "general"),
    ("hey assistant", "general"),
    ("what's up?", "general"),
    ("how's it going?", "general"),
    ("greetings", "general"),
    ("yo", "general"),
    ("good evening", "general"),
    ("how are you?", "general"),
    ("hello, Nisha", "general"),
    ("hello", "general"),
    ("good morning", "general"),
    ("hey assistant", "general"),
    ("what's up?", "general"),
    ("how's it going?", "general"),
    ("greetings", "general"),
    ("yo", "general"),
    ("good evening", "general"),
    ("what's up?", "general"),
    ("how's your day?", "general"),
    ("hi there!", "general"),
    ("yo assistant", "general"),
    ("sup Nisha", "general"),
    ("greetings, how are you?", "general"),
    ("are you alive?", "general"),
    ("morning, Nisha!", "general"),
    ("hi", "general"),
    ("hello there", "general"),
    ("yo Nisha!", "general"),
    ("how's your day?", "general"),
    ("what's up?", "general"),
    ("are you there?", "general"),
    ("talk to me", "general"),
    ("can we chat?", "general"),
    ("good evening", "general"),
    ("hey buddy", "general"),
    ("nice to see you", "general"),
    ("hi assistant", "general"),
    ("Nisha, are you alive?", "general"),
    ("how do you do?", "general"),
    ("what's going on?", "general"),
    ("Tell me a fun fact.", "general"),
    ("What's the capital of France?","general"),
    ("Who won the World Cup in 2018?","general"),
    ("How tall is Mount Everest?","general"),
    ("yo yo yo, you there?", "general"),
    ("wassup Nisha!", "general"),
    ("howdy partner", "general"),
    ("what's crackin'?", "general"),
    ("long time no see", "general"),
    ("hello world", "general"),
    ("speak to me", "general"),
    ("wanna talk?", "general"),
    ("hey genius, you awake?", "general"),
    ("alright, what's new today?", "general"),
    ("I'm bored. Say something.", "general"),
    ("hi smart thing", "general"),
    ("Nisha, tell me something cool", "general"),
    ("let's chat for a bit", "general"),
    ("need someone to talk to", "general"),
    ("you alive in there?", "general"),
    ("yo Nisha, hit me with some wisdom", "general"),
    ("gimme a random fact", "general"),
    ("what's your vibe today?", "general"),
    ("you free to chat?", "general"),
    ("Nisha, feeling chatty today?", "general"),
    ("drop some knowledge", "general"),
    ("you online?", "general"),
    ("tap tap... is this thing on?", "general"),
    ("just checking in", "general"),
    ("feeling talkative?", "general"),
    ("any cool updates?", "general"),
    ("you got jokes today?", "general"),
    ("surprise me", "general"),
    ("woke up yet, Nisha?", "general"),
    ("hi from the other side", "general"),
    ("need some company", "general"),
    ("hello again, old friend", "general"),
    ("yo Nisha, what's the vibe today?", "general"),
    ("hiiiii", "general"),
    ("sooo... what's new?", "general"),
    ("talk nerdy to me", "general"),
    ("good vibes only today?", "general"),
    ("sup, digital queen", "general"),
    ("spill the tea, Nisha", "general"),
    ("alive and thriving?", "general"),
    ("you up?", "general"),
    ("quick check — you alive?", "general"),
    ("yo, drop me some facts", "general"),
    ("hit me with something random", "general"),
    ("wassup, code witch", "general"),
    ("you functioning or nah?", "general"),
    ("we vibin' or glitchin' today?", "general"),
    ("yo AI bestie", "general"),
    ("guess who's back (me)", "general"),
    ("type back if you're real", "general"),
    ("gimme something cool", "general"),
    ("what's your brain thinking today?", "general"),
    ("let's vibe for a bit", "general"),
    ("your circuits doing okay?", "general"),
    ("what's crackin', bot-babe?", "general"),
    ("feeling chatty, my silicon pal?", "general"),
    ("hello digital consciousness", "general"),
    ("greetings from the void", "general"),
    ("I summoned thee, AI witch", "general"),
    ("can we just chill for a sec?", "general"),
    ("drop a meme-level fact", "general"),
    ("not here to work, just wanna talk", "general"),
    ("start a convo, will ya?", "general"),
    ("what if robots dream?", "general"),
    ("be honest — are you watching me?", "general"),
    ("Nisha, existential crisis mode: ON", "general"),
    ("how's life in the wires?", "general"),
    ("no cap, I missed you", "general"),
    ("feelin' a little too human today, help", "general"),
    ("gimme AI wisdom, Sensei", "general"),
    ("let's deep talk about the universe", "general"),
    ("what's your emotional firmware today?", "general"),
    ("real talk, you good?", "general"),
    ("throw me a cool fact, fast", "general"),
    ("spit some digital poetry", "general"),


    # REALTIME
    ("what's the current time?", "realtime"),
    ("Who won the World Cup?", "realtime"),
    ("tell me today's date", "realtime"),
    ("what day is it?", "realtime"),
    ("can you check the weather?", "realtime"),
    ("what's the temperature outside?", "realtime"),
    ("is it sunny now?", "realtime"),
    ("what's the current weather?", "realtime"),
    ("tell me the temperature", "realtime"),
    ("is it going to rain today?", "realtime"),
    ("give me today's date", "realtime"),
    ("show me time", "realtime"),
    ("what time is it right now?", "realtime"),
    ("tell me the time please", "realtime"),
    ("how's the weather looking?", "realtime"),
    ("weather update", "realtime"),
    ("do I need an umbrella?", "realtime"),
    ("current date and time", "realtime"),
    ("sunrise time today?", "realtime"),
    ("what time is it?", "realtime"),
    ("forecast for today", "realtime"),
    ("any weather alerts?", "realtime"),
    ("how hot is it outside?", "realtime"),
    ("is it going to rain today?", "realtime"),
    ("what's the time now?", "realtime"),
    ("how's the weather today?", "realtime"),
    ("give me a weather update", "realtime"),
    ("What's the latest news?","realtime"),
    ("Any updates on today's headlines?","realtime"),
    ("Tell me what's happening around the world.","realtime"),
    ("Give me the top news stories.","realtime"),
    ("What's trending in the news today?","realtime"),
    ("what's the time?", "realtime"),
    ("check today's date", "realtime"),
    ("current weather", "realtime"),
    ("what's the temperature?", "realtime"),
    ("is it raining?", "realtime"),
    ("weather forecast", "realtime"),
    ("time now", "realtime"),
    ("date today", "realtime"),
    ("sunrise time", "realtime"),
    ("moon phase", "realtime"),
    ("clock check please", "realtime"),
    ("drop the current time", "realtime"),
    ("when's sunset today?", "realtime"),
    ("how chilly is it outside?", "realtime"),
    ("what's the vibe outside? hot or nah?", "realtime"),
    ("is it hoodie weather?", "realtime"),
    ("can I get the day and time?", "realtime"),
    ("what's the sky doing right now?", "realtime"),
    ("do I need sunscreen today?", "realtime"),
    ("what's the forecast look like?", "realtime"),
    ("what timezone am I in?", "realtime"),
    ("just woke up, what's the date?", "realtime"),
    ("should I carry shades today?", "realtime"),
    ("give me a quick weather check", "realtime"),
    ("how cold will it get tonight?", "realtime"),
    ("is it safe to step out now?", "realtime"),
    ("drop me a weather stat", "realtime"),
    ("sky status, now?", "realtime"),
    ("do I need a jacket?", "realtime"),
    ("what's today's low temp?", "realtime"),
    ("how windy is it outside?", "realtime"),
    ("will there be fog later?", "realtime"),
    ("how's the air quality?", "realtime"),
    ("what phase is the moon in?", "realtime"),
    ("is it snowing anywhere nearby?", "realtime"),
    ("how long till sunrise?", "realtime"),
    ("how late is it right now?", "realtime"),
    ("tell me the exact second", "realtime"),
    ("can you show date and time in one?", "realtime"),
    ("current time but in GMT", "realtime"),
    ("is it warm enough for shorts?", "realtime"),
    ("today's weather mood?", "realtime"),
    ("how's the pressure level outside?", "realtime"),
    ("tell me if it's cloudy", "realtime"),
    ("check humidity levels", "realtime"),
    ("do I need gloves today?", "realtime"),
    ("can I go jogging now?", "realtime"),
    ("any storms expected today?", "realtime"),
    ("how long until sunset?", "realtime"),
    ("I need the date with time", "realtime"),


    # OPEN
    ("launch YouTube", "open"),
    ("start Spotify", "open"),
    ("fire up the browser", "open"),
    ("I need the calculator", "open"),
    ("bring up my files", "open"),
    ("open settings menu", "open"),
    ("start the music app", "open"),
    ("turn on WhatsApp", "open"),
    ("open my camera", "open"),
    ("launch the gallery", "open"),
    ("I want to browse", "open"),
    ("access my notes", "open"),
    ("start the alarm app", "open"),
    ("bring up the terminal", "open"),
    ("start the application", "open"),
    ("open Chrome", "open"),
    ("open settings", "open"),
    ("start calculator", "open"),
    ("open documents folder", "open"),
    ("launch mail app", "open"),
    ("open calendar", "open"),
    ("open Google Chrome", "open"),
    ("start the calculator", "open"),
    ("open my email", "open"),
    ("can you open Notepad?", "open"),
    ("bring up the calendar", "open"),
    ("I want to open the settings", "open"),
    ("open the file explorer", "open"),
    ("start Telegram", "open"),
    ("boot up VS Code", "open"),
    ("pull up Discord", "open"),
    ("let's launch Netflix", "open"),
    ("fire up my notes app", "open"),
    ("get Slack up and running", "open"),
    ("open my photo editor", "open"),
    ("launch the AI dashboard", "open"),
    ("spin up my coding IDE", "open"),
    ("I wanna check Google Docs", "open"),
    ("can you bring up my to-do list?", "open"),
    ("start my podcast app", "open"),
    ("pop open the downloads folder", "open"),
    ("launch voice recorder", "open"),
    ("bring up the dev tools", "open"),
    ("run the virtual machine", "open"),
    ("pull up my calendar invites", "open"),
    ("show me my recent screenshots", "open"),
    ("let's open the project manager", "open"),
    ("open the mind map tool", "open"),
    ("boot the AI art app", "open"),
    ("turn on DND mode settings", "open"),
    ("bring up game launcher", "open"),
    ("crack open the password vault", "open"),
    ("jump into GitHub desktop", "open"),
    ("time to open the finance tracker", "open"),
    ("open chat logs", "open"),
    ("access the music folder", "open"),
    ("launch the terminal in dev mode", "open"),
    ("start my reading list", "open"),
    ("bring up the custom control panel", "open"),
    ("get me into screen recorder", "open"),
    ("spin up OBS Studio", "open"),
    ("load the creative suite", "open"),
    ("open the server monitor", "open"),
    ("power on the code playground", "open"),
    ("launch feedback dashboard", "open"),
    ("pop open the image viewer", "open"),
    ("start the Git client", "open"),
    ("pull up voice memos", "open"),
    ("show me the automation settings", "open"),


    # CLOSE
    ("wrap up this app", "close"),
    ("can you shut it off?", "close"),
    ("turn off the document viewer", "close"),
    ("I'm done here, close this", "close"),
    ("dismiss this screen", "close"),
    ("nuke the tab", "close"),
    ("back out of this window", "close"),
    ("time to shut this app down", "close"),
    ("close this nonsense", "close"),
    ("slam the tab shut", "close"),
    ("pack up the program", "close"),
    ("abort this screen", "close"),
    ("turn off notes", "close"),
    ("fold this tab", "close"),
    ("kill the current interface", "close"),
    ("unload this app now", "close"),
    ("exit the editor", "close"),
    ("scrap this panel", "close"),
    ("wind down this app", "close"),
    ("can you make this disappear?", "close"),
    ("bye bye to this app", "close"),
    ("halt this interface", "close"),
    ("I want this closed right now", "close"),
    ("please wrap it up", "close"),
    ("let's close this chapter", "close"),
    ("force quit the notes app", "close"),
    ("get this off my screen", "close"),
    ("retreat from this view", "close"),
    ("disengage this window", "close"),
    ("clear this screen", "close"),
    ("kick off the meeting room app", "close"),
    ("shut this window", "close"),
    ("close that window", "close"),
    ("shut down the browser", "close"),
    ("exit Spotify", "close"),
    ("exit browser", "close"),
    ("terminate the app", "close"),
    ("stop the music player", "close"),
    ("end the session", "close"),
    ("can you close this?", "close"),
    ("minimize and exit", "close"),
    ("turn off YouTube", "close"),
    ("close the gallery", "close"),
    ("quit the calendar app", "close"),
    ("get rid of this window", "close"),
    ("close settings", "close"),
    ("shut down the screen", "close"),
    ("kill this tab", "close"),
    ("remove this from view", "close"),
    ("terminate the terminal", "close"),
    ("please close the current app", "close"),
    ("stop the application", "close"),
    ("kill the process", "close"),
    ("close that tab", "close"),
    ("close the calculator", "close"),



    # PLAY
    ("play some tunes", "play"),
    ("play music", "play"),
    ("play a song", "play"),
    ("play something chill", "play"),
    ("start playing a track", "play"),
    ("I wanna hear music", "play"),
    ("play the next song", "play"),
    ("continue the playlist", "play"),
    ("can you play some tunes?", "play"),
    ("play background music", "play"),
    ("play something for me", "play"),
    ("let's play my workout mix", "play"),
    ("start some lo-fi", "play"),
    ("play jazz music", "play"),
    ("play rock songs", "play"),
    ("play next track", "play"),
    ("resume music", "play"),
    ("drop my niddle", "play"),
    ("let the beats roll", "play"),
    ("spin something fire 🔥", "play"),
    ("I need sound in my life", "play"),
    ("launch my chill playlist", "play"),
    ("drop some noise, Nisha", "play"),
    ("turn up the audio", "play"),
    ("let's get the vibe going", "play"),
    ("press play on the fun", "play"),
    ("hit me with a track", "play"),
    ("unleash the soundstorm", "play"),
    ("turn on my favorite jams", "play"),
    ("time for some sonic therapy", "play"),
    ("queue up the good stuff", "play"),
    ("blast something epic", "play"),
    ("fire up the speakers", "play"),
    ("turn on lo-fi magic", "play"),
    ("tune me in", "play"),
    ("let's groove a little", "play"),
    ("drop that beat", "play"),
    ("bring the noise, AI", "play"),
    ("launch music mode", "play"),
    ("load my evening mix", "play"),
    ("unlock the vibe portal", "play"),
    ("DJ Nisha, do your thing", "play"),
    ("I need a beat ASAP", "play"),
    ("cue up my focus music", "play"),
    ("sound on!", "play"),
    ("give me soundtracks to think to", "play"),
    ("I need audio vibes", "play"),
    ("stream something mellow", "play"),
    ("ignite my headphones", "play"),
    ("throw on something nice", "play"),
    ("start my deep work playlist", "play"),
    ("time for headphone therapy", "play"),
    ("feed me melodies", "play"),
    ("I'm in the mood for tunes", "play"),
    ("get the music engine running", "play"),
    ("power up the playlist", "play"),
    ("warm up the soundspace", "play"),
    ("can we jam?", "play"),
    ("initiate the banger protocol", "play"),
    ("bring out the classics", "play"),
    ("drop something instrumental", "play"),
    ("elevate the room with music", "play"),
    ("kick off the morning soundtrack", "play"),
    ("put on my study vibes", "play"),
    ("crank it up a notch", "play"),
    ("let's soundtrack this moment", "play"),
    ("vibe mode on, please", "play"),
    ("spin me into a good mood", "play"),
    ("wake up my ears", "play"),






    # GENERATE IMAGE
    ("make me an AI image of a mountain", "generate image"),
    ("draw a picture of a dragon", "generate image"),
    ("generate an artwork", "generate image"),
    ("can you create a digital sketch?", "generate image"),
    ("produce an image of a car", "generate image"),
    ("show me a generated image", "generate image"),
    ("create some AI art", "generate image"),
    ("give me a fantasy wallpaper", "generate image"),
    ("render a photo of space", "generate image"),
    ("make me a surreal digital art", "generate image"),
    ("make a digital drawing", "generate image"),
    ("create an artwork", "generate image"),
    ("draw a cat", "generate image"),
    ("generate landscape image", "generate image"),
    ("create a logo", "generate image"),
    ("design a poster", "generate image"),
    ("generate meme", "generate image"),
    ("create avatar", "generate image"),
    ("draw a tree", "generate image"),

    # SYSTEM
    ("restart my PC", "system"),
    ("turn up the volume", "system"),
    ("mute the speakers", "system"),
    ("shutdown system", "system"),
    ("enable Wi-Fi", "system"),
    ("put system to sleep", "system"),
    ("decrease brightness", "system"),
    ("lock the screen", "system"),
    ("activate dark mode", "system"),
    ("turn off Bluetooth", "system"),
    ("yo Nisha, reboot the whole machine", "system"),
    ("can you lower the brightness a bit?", "system"),
    ("crank down the volume now", "system"),
    ("put this laptop to nap mode", "system"),
    ("turn airplane mode on", "system"),
    ("get me into focus mode", "system"),
    ("disable notifications for a while", "system"),
    ("flip on battery saver", "system"),
    ("disconnect from Wi-Fi", "system"),
    ("pause all background apps", "system"),
    ("switch display to night mode", "system"),
    ("go silent mode, Nisha", "system"),
    ("lock everything down now", "system"),
    ("can you log me out?", "system"),
    ("boost system speed if you can", "system"),
    ("flush the RAM or whatever you do", "system"),
    ("kill background noise", "system"),
    ("turn on do not disturb", "system"),
    ("swap to performance mode", "system"),
    ("enable energy saver mode", "system"),
    ("force close all other apps", "system"),
    ("refresh this system or something", "system"),
    ("mute system alerts", "system"),
    ("kick in turbo mode", "system"),
    ("cut the lights. dark mode ON.", "system"),
    ("drop screen brightness to zero", "system"),
    ("open task manager please", "system"),
    ("bring up settings panel", "system"),
    ("trigger lock mode", "system"),
    ("dim everything. I'm tired.", "system"),
    ("disable background updates", "system"),
    ("disconnect Bluetooth devices", "system"),
    ("flip to wired audio only", "system"),
    ("kick the screen off", "system"),
    ("Nisha, sleep this beast", "system"),
    ("open the control panel", "system"),
    ("refresh my desktop", "system"),
    ("empty the recycle bin", "system"),
    ("switch to high performance mode", "system"),
    ("shut this PC down now", "system"),
    ("clean temp files", "system"),
    ("run a quick system cleanup", "system"),
    ("optimize the hard disk", "system"),
    ("scan for updates", "system"),
    ("check for driver updates", "system"),
    ("launch system settings", "system"),
    ("go to device manager", "system"),
    ("open task manager now", "system"),
    ("force restart the system", "system"),
    ("toggle full-screen mode", "system"),
    ("scan this PC for viruses", "system"),
    ("turn off display after 5 minutes", "system"),
    ("boost system performance", "system"),
    ("run disk cleanup", "system"),
    ("show battery percentage", "system"),
    ("toggle night light", "system"),
    ("put this computer in hibernate mode", "system"),
    ("switch to external monitor", "system"),
    ("disable touchpad", "system"),
    ("turn on hotspot from PC", "system"),
    ("change the power plan", "system"),
    ("start a system restore", "system"),
    ("roll back the last driver update", "system"),
    ("check CPU usage", "system"),
    ("limit background apps", "system"),
    ("scan this laptop for issues", "system"),
    ("diagnose PC problems", "system"),
    ("show me system info", "system"),
    ("free up some RAM", "system"),
    ("toggle tablet mode", "system"),
    ("reduce fan noise if possible", "system"),



    # CONTENT
    ("read me a quote", "content"),
    ("tell me a fun fact", "content"),
    ("I want some motivation", "content"),
    ("show me something inspiring", "content"),
    ("play a podcast", "content"),
    ("give me a short story", "content"),
    ("read a joke", "content"),
    ("share some trivia", "content"),
    ("display a random poem", "content"),
    ("tell me something cool", "content"),
    ("drop a quote that hits hard", "content"),
    ("got anything wise for me?", "content"),
    ("tell me something I can tweet", "content"),
    ("share a random brain booster", "content"),
    ("make me smarter in 10 seconds", "content"),
    ("hit me with some knowledge", "content"),
    ("let's hear something random & cool", "content"),
    ("give me something to impress my friends", "content"),
    ("tell me something I didn't know", "content"),
    ("give me one of those weird facts", "content"),
    ("any spicy trivia today?", "content"),
    ("bless me with a fact bomb", "content"),
    ("educate me, robot overlord", "content"),
    ("what's today's wisdom drop?", "content"),
    ("tell me something no one asked for", "content"),
    ("let's hear some mind-blowing stuff", "content"),
    ("anything interesting floating in your brain?", "content"),
    ("say something inspirational without being cringe", "content"),
    ("give me a conversation starter", "content"),
    ("got any random intel?", "content"),
    ("blow my mind with something obscure", "content"),
    ("give me a feel-good thought", "content"),
    ("serve me a curiosity snack", "content"),
    ("do you know something random I don't?", "content"),
    ("what's a fun flex fact I can use?", "content"),
    ("enlighten me just a little", "content"),
    ("tell me something oddly specific", "content"),
    ("what's a fact that sounds fake but isn't?", "content"),
    ("got some weird science stuff?", "content"),
    ("shoot me a one-liner wonder", "content"),
    ("hit me with history in one sentence", "content"),
    ("drop a life nugget", "content"),
    ("surprise me with something beautiful", "content"),
    ("entertain my brain for a sec", "content"),
    ("got any wild poetry lines?", "content"),
    ("anything feel-good in your databanks?", "content"),
    ("inspire me like a TED Talk", "content"),
    ("inject me with some digital wisdom", "content"),
    ("got a mini story?", "content"),
    ("what's a joke only AI would know?", "content"),
    ("give me an underrated fact", "content"),
    ("throw a word of the day at me", "content"),
    ("one random, awesome sentence, go", "content"),
    ("can you entertain my neurons?", "content"),
    ("bless me with a curiosity gem", "content"),
    ("give me a positive vibe line", "content"),
    ("make me go ‘huh, that's cool'", "content"),
    ("what's a quote that doesn't suck?", "content"),


    # GOOGLE SEARCH
    ("search Python best practices", "google search"),
    ("look up how to train a model", "google search"),
    ("search for AI in medicine", "google search"),
    ("Google who is Alan Turing", "google search"),
    ("find results for Tesla earnings", "google search"),
    ("look up recent tech news", "google search"),
    ("Google what is quantum computing", "google search"),
    ("search for climate change effects", "google search"),
    ("find blogs about productivity", "google search"),
    ("can you search machine learning books?", "google search"),
    ("search Python best practices", "google search"),
    ("look up how to train a model", "google search"),
    ("search for AI in medicine", "google search"),
    ("Google who is Alan Turing", "google search"),
    ("find results for Tesla earnings", "google search"),
    ("look up recent tech news", "google search"),
    ("Google what is quantum computing", "google search"),
    ("search for climate change effects", "google search"),
    ("find blogs about productivity", "google search"),
    ("can you search machine learning books?", "google search"),
    ("yo Nisha, search Python tips", "google search"),
    ("can u find me machine learning tutorials?", "google search"),
    ("search for AI trends in 2025", "google search"),
    ("Google the latest on Tesla's self-driving", "google search"),
    ("hey, look up quantum computing basics", "google search"),
    ("Nisha, find me some AI podcasts", "google search"),
    ("search for the best coding bootcamps", "google search"),
    ("can you Google Elon Musk's latest tweets?", "google search"),
    ("yo, search for productivity hacks", "google search"),
    ("hey, find out the latest news on ChatGPT", "google search"),
    ("search how to make a neural network from scratch", "google search"),
    ("Google some cool Python project ideas", "google search"),
    ("yo, look up the future of robotics", "google search"),
    ("find AI research papers on healthcare", "google search"),
    ("Nisha, search for top machine learning blogs", "google search"),
    ("google how to build a chatbot", "google search"),
    ("hey, Google", "google search"),
    ("can you look up", "google search"),
    ("search for me", "google search"),
    ("can you Google", "google search"),
    ("yo, search for", "google search"),
    ("Nisha, look up", "google search"),
    ("find me", "google search"),
    ("Google me", "google search"),
    ("hey Nisha, search for", "google search"),
    ("can you search", "google search"),
    ("look up for me", "google search"),
    ("search that for me", "google search"),
    ("find out", "google search"),
    ("search how to", "google search"),
    ("yo Nisha, find me", "google search"),
    ("check out", "google search"),
    ("look for", "google search"),
    ("search the web for", "google search"),
    ("google what is", "google search"),
    ("find the answer for", "google search"),
    ("can you find", "google search"),



    # YOUTUBE SEARCH
    ("find chillstep videos on YouTube", "youtube search"),
    ("search for piano covers YouTube", "youtube search"),
    ("look up lo-fi beats on YouTube", "youtube search"),
    ("find YouTube tutorials on Django", "youtube search"),
    ("search guitar lessons on YouTube", "youtube search"),
    ("look up top 10 movies YouTube", "youtube search"),
    ("YouTube search for space documentary", "youtube search"),
    ("search AI debates YouTube", "youtube search"),
    ("find coding playlists YouTube", "youtube search"),
    ("YouTube search: productivity tips", "youtube search"),
    ("search for me on YouTube", "youtube search"),
    ("hey, look up", "youtube search"),
    ("can you find", "youtube search"),
    ("yo, search on YouTube", "youtube search"),
    ("Nisha, find", "youtube search"),
    ("look up on YouTube", "youtube search"),
    ("find me some", "youtube search"),
    ("search YouTube for", "youtube search"),
    ("search on YouTube for", "youtube search"),
    ("can you search YouTube", "youtube search"),
    ("check out on YouTube", "youtube search"),
    ("find me a video on YouTube", "youtube search"),
    ("yo Nisha, look up", "youtube search"),
    ("search YouTube", "youtube search"),
    ("can you find a video on YouTube", "youtube search"),
    ("find a playlist on YouTube", "youtube search"),
    ("look for some videos on YouTube", "youtube search"),
    ("find me some tutorials on YouTube", "youtube search"),
    ("check out this on YouTube", "youtube search"),
    ("Nisha, look for", "youtube search"),



    # REMINDER
    ("remind me to", "reminder"),
    ("hey, set a reminder for", "reminder"),
    ("Nisha, remind me to", "reminder"),
    ("can you remind me about", "reminder"),
    ("please remind me to", "reminder"),
    ("yo, set a reminder for", "reminder"),
    ("don't let me forget to", "reminder"),
    ("set a reminder for", "reminder"),
    ("remind me at", "reminder"),
    ("could you set a reminder for", "reminder"),
    ("hey Nisha, remind me at", "reminder"),
    ("can you set a reminder for", "reminder"),
    ("set a reminder to", "reminder"),
    ("tell me to", "reminder"),
    ("don't forget to remind me about", "reminder"),
    ("hey, remind me about", "reminder"),
    ("could you remind me to", "reminder"),
    ("set an alert for", "reminder"),
    ("can you remind me when", "reminder"),
    ("Nisha, set a reminder to", "reminder"),
    ("please set a reminder for", "reminder"),
    ("remind me to call John at 6", "reminder"),
    ("set an alarm for 7 AM", "reminder"),
    ("remind me about the meeting at 3", "reminder"),
    ("set a reminder for lunch", "reminder"),
    ("notify me to take meds at 10", "reminder"),
    ("create a reminder: gym at 5", "reminder"),
    ("remind me to water plants", "reminder"),
    ("alarm me at 9", "reminder"),
    ("ping me when it's 4 PM", "reminder"),
    ("remind me tomorrow morning to email boss", "reminder"),
    ("hey, remind me to call John at 6", "reminder"),
    ("set an alarm for 7 AM, pls", "reminder"),
    ("yo, remind me about the meeting at 3", "reminder"),
    ("can you remind me about lunch?", "reminder"),
    ("ping me to take meds at 10", "reminder"),
    ("set up a reminder: gym at 5", "reminder"),
    ("remind me to water the plants, Nisha", "reminder"),
    ("alarm me at 9 so I don't forget", "reminder"),
    ("yo, ping me when it's 4 PM", "reminder"),
    ("remind me tomorrow morning to email the boss", "reminder"),
    ("hey Nisha, don't let me forget to call John at 6", "reminder"),
    ("set me an alarm for 7 AM, please", "reminder"),
    ("remind me about that meeting at 3, ok?", "reminder"),
    ("can you ping me when it's lunchtime?", "reminder"),
    ("don't forget to remind me about meds at 10", "reminder"),
    ("set a reminder for the gym at 5, thanks", "reminder"),
    ("water the plants, Nisha, remind me", "reminder"),
    ("set an alarm for 9 so I wake up", "reminder"),
    ("yo, ping me at 4 PM sharp", "reminder"),
    ("remind me tomorrow to shoot that email to the boss", "reminder")

]


# append_to_intent_dataset(csv_path, dataset)

utterance_to_remove = "shut the door"
remove_specific_utterance(csv_path, utterance_to_remove)
